---
layout: post
title: Research - Error Handling within C++ (via LLVM)
---
https://llvm.org/docs/ExceptionHandling.html

There are two main approaches to exception handling discussed by the LLVM docs:
1. `setjmp/longjmp` (SJLJ) Exception Handling
2. Itanium ABI Zero-cost Exception Handling
(There's also an extra handling measure for Windows, but I'm not using Windows, so woohoo)

My main goal before March is simply to have a `throw` function. Stack traces & exception handling are cool, but that is way too much work for March.

# SJLJ

This essentially uses gotos, and only requires C's runtime.

It involves two functions:

```llvm
declare i32 @llvm.eh.sjlj.setjmp(ptr %setjmp_buf)
```

* Writes a `jmp_buf` (C type) into `%setjmp_buf`. This can later be used by `longjmp` to return to this point in the function.
* The `i32` is 0 if this is the first execution of `setjmp`. Otherwise, it is an entry from `longjmp`.

```llvm
declare void @llvm.eh.sjlj.longjmp(ptr %setjmp_buf)
```
* Accesses the `jmp_buf`, and goes to the associated `setjmp` and resumes the program from there.

In C, we have an example such as
```c
#include <stdio.h>
#include <setjmp.h>
#include <stdnoreturn.h>
 
jmp_buf my_jump_buffer;
 
noreturn void foo(int status) 
{
    printf("foo(%d) called\n", status);
    longjmp(my_jump_buffer, status + 1); // will return status+1 out of setjmp
}
 
int main(void)
{
    volatile int count = 0; // modified local vars in setjmp scope must be volatile
    if (setjmp(my_jump_buffer) != 5) // compare against constant in an if
        foo(++count);
}
```
(from https://en.cppreference.com/w/c/program/longjmp)

When converted to LL bytecode, 
```llvm
@.str = private unnamed_addr constant [16 x i8] c"foo(%d) called\0A\00", align 1
@my_jump_buffer = global [37 x i32] zeroinitializer, align 16

; Function Attrs: noinline noreturn nounwind optnone ssp uwtable
define void @foo(i32 noundef %0) #0 {
  %2 = alloca i32, align 4
  store i32 %0, ptr %2, align 4
  %3 = load i32, ptr %2, align 4
  %4 = call i32 (ptr, ...) @printf(ptr noundef @.str, i32 noundef %3)
  %5 = load i32, ptr %2, align 4
  %6 = add nsw i32 %5, 1

  ; longjmp called, and then unreachable is called to indicate 
  ; this function will not return
  call void @longjmp(ptr noundef @my_jump_buffer, i32 noundef %6) #5
  unreachable
}

declare i32 @printf(ptr noundef, ...) #1

; Function Attrs: noreturn
declare void @longjmp(ptr noundef, i32 noundef) #2

; Function Attrs: noinline nounwind optnone ssp uwtable
define i32 @main() #3 {
  %1 = alloca i32, align 4
  store volatile i32 0, ptr %1, align 4

  ; if %2 is <5, call the fn
  ; if %2 is >= 5, exit
  %2 = call i32 @setjmp(ptr noundef @my_jump_buffer) #6
  %3 = icmp ne i32 %2, 5
  br i1 %3, label %4, label %7

4:                                                ; preds = %0
  %5 = load volatile i32, ptr %1, align 4
  %6 = add nsw i32 %5, 1
  store volatile i32 %6, ptr %1, align 4
  call void @foo(i32 noundef %6) #5
  unreachable

7:                                                ; preds = %0
  ret i32 0
}

; Function Attrs: returns_twice
declare i32 @setjmp(ptr noundef) #4
```

For a `try/catch` (which, I reiterate, I'm not trying to implement), you could do something such as...
```c
#include <stdio.h>
#include <setjmp.h>
#include <stdnoreturn.h>
 
jmp_buf err_buf;
 
noreturn void foo(int status) 
{
    printf("foo(%d) called\n", status);
    longjmp(err_buf, 1);
}
 
int main(void)
{
    int E;
    // try
    if ((E = setjmp(my_jump_buffer)) == 0)
        foo(0);
    // catch exceptions in E
    else
	    /* do something with E */
}
```

>[!Info] Pros & Cons
> ### Pros
> * Doesn't require C++ runtime
> * Pretty simple to understand
> 
> ### Cons
> * Every single function's error has to be handled by a singular main function & jump buffer?
> * Setting up does require runtime cost
> * Stack traces are pretty much impossible (or VERY cumbersome)

# Itanium ABI

https://subscription.packtpub.com/book/cloud-and-networking/9781839213502/9/ch09lvl1sec48/throwing-and-catching-exceptions

LLVM has first-class(ish) support for this. It's a zero-cost method for unwinding through errors.

## Catching Exceptions

### `invoke`

To start, we have the `invoke` instruction. It is similar to `call`:
```llvm
<result> = call <ty>|<fnty> <fnptrval>(<function args>) [fn attrs]

<result> = invoke <ty>|<fnty> <fnptrval>(<function args>) [fn attrs]
	to label <normal label> unwind label <exception label>
```
*Note: I only included relevant details of the two functions. See the LLVM Language Reference for more details.*

The `invoke` instruction works similarly to `call`, except it catches errors and interrupts the unwinding process. (`call` will propagate errors up the function stack.)
* If the call was successful, `invoke` branches to `<normal label>`. 
* If the call raised an exception, it branches to `<exception label>`.

In pseudocode terms, `invoke` is
```java
try {       // <-- THIS
	call()  // <-- THIS
} catch (/* ... */) {
	/* ... */
}
```

### `landingpad`

The `<exception label>` HAS to start with a `landingpad` instruction.
```llvm
<resultval> = landingpad <resultty> <clause>+
<resultval> = landingpad <resultty> cleanup <clause>*

<clause> := catch <type> <value>
<clause> := filter <array constant type> <array constant>
```

>[!Example]
> A possible `landingpad` instruction in C++ LLVM IR would take the form
> ```llvm
>    %result = landingpad { ptr, i8 }
>		catch ptr @_ZTIi
> ```
>
> The type `{ ptr, i8 }` holds the exception value (as a `ptr`) and a discriminant (as `i8`).
> - In C++, this discriminant is `@llvm.eh.typeid.for(ptrÂ @ExcType)`.
> 
> We're *only* catching ints, so we catch a `ptr` of type `@_ZTIi` (the `std::type_info` for int).
> - *Note*: How do you compute type_info for arbitrary types?

Additionally, we can use `cleanup` to catch all exceptions.

To use the exception, we have to use:
```llvm
declare ptr @__cxa_begin_catch(ptr %exc.ptr)
```

This pulls our payload from the landingpad `%result` pointer field, and we can manipulate it to do whatever.

We should then destroy the exception via
```llvm
declare void @__cxa_end_catch()
```
and then `ret`.

Alternatively, we can rethrow the exception via
```llvm
declare void @__cxa_rethrow()
```

The `resume` instruction can be used to repropagate an error that hasn't been loaded via `@__cxa_begin_catch`. We'd use the selector to check the exception type and then act accordingly.

## Throwing Exceptions

We first need to construct an exception. We can do this with
```llvm
declare ptr @__cxa_allocate_exception(i64 %len)
```

This is `malloc` for exceptions.

Then, we can throw the exception with
```llvm
declare void @__cxa_throw(ptr %exc, ptr %type_info, ptr dest)
```
This accepts three arguments:
- The ptr to the exception value (which we generated)
- The ptr to the type_info (for int, it would be `@_ZTIi`)
- idk. It's null in the examples, so `null`?

## Personality

Finally, we need to indicate a `personality` for each function that can error.
This personality function analyzes how the exception should be dealt with in each propagation.

For every function that can unwind, we need to include `personality ptr @__gxx_personality_v0`.

>[!Info] Pros & Cons
> ### Pros
> * Supported by LLVM & significantly less hacky
> * Modular, does not require every function to have a global ptr to report an error to
> 
> ### Cons
> * C++ runtime
> 	* Bunch of functions! `__cxa_allocate_exception`, `__cxa_throw`, `__gxx_personality_v0`, etc.
> 	* Dealing with `std::type_info`
